#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#45F1C2'
    template = ' {{ .UserName }} on'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#0CA0D8'
    template = '  {{ .Path }} '

    [blocks.segments.properties]
      folder_separator_icon = '/'
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    powerline_symbol = ''
    foreground = '#14A5AE'
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = '#cd5e42'
    template = ' '

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#CD4277'
    template = '# '
