[shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5}
dynamic_padding = false
decorations = "None"
opacity = 1
blur = false
startup_mode = "Windowed"
title = "Hola mundo"
dynamic_title = true
decorations_theme_variant = "Dark"
resize_increments = false

[font]
normal = { family = "MonaspiceNe Nerd Font", style = "Regular"}
bold = { family = "MonaspiceNe Nerd Font", style = "Bold"}
italic = { family = "MonaspiceNe Nerd Font", style = "Italic"}
bold_italic = { family = "MonaspiceNe Nerd Font", style = "Bold Italic"}
size = 14
builtin_box_drawing = false

[colors]
[colors.primary]
background = '#1a212e'
foreground = '#abb2bf'
[colors.normal]
black = '#0c0e15'
red = '#f65866'
green = '#8bcd5b'
yellow = '#efbd5d'
blue = '#41a7fc'
magenta = '#c75ae8'
cyan = '#34bfd0'
white = '#93a4c3'
[colors.bright]
black = '#455574'
red = '#f65866'
green = '#8bcd5b'
yellow = '#efbd5d'
blue = '#41a7fc'
magenta = '#c75ae8'
cyan = '#34bfd0'
white = '#abb2bf'

